### ISSUE TITLE
飞浆上对strongbaseline的mA达到了94.86，请问作者有什么见解它是如何做到的呢？

### ISSUE THREAD

**Issue by zhouyuchong** [valencebond/Rethinking_of_PAR#11]
如题，最近飞浆的pphuman里面的属性识别，模型应该是用的strongbaseline，但是其mA和速度都得到了大幅度优化？请问您有头绪吗

**Comment by valencebond** [comment]
我没有仔细看过 pphuman, 但根据 文档所述，”行人属性分析精度为[PA100k](https://github.com/xh-liu/HydraPlus-Net#pa-100k-dataset)，[RAPv2](http://www.rapdataset.com/rapv2.html)，[PETA](http://mmlab.ie.cuhk.edu.hk/projects/PETA.html)和部分业务数据融合训练测试得到“。这部分业务数据应该起了很重要的作用。

**Comment by zhouyuchong** [comment]
感谢回复 
我先去自己看看

**Comment by clw5180** [comment]
> 我没有仔细看过 pphuman, 但根据 文档所述，”行人属性分析精度为[PA100k](https://github.com/xh-liu/HydraPlus-Net#pa-100k-dataset)，[RAPv2](http://www.rapdataset.com/rapv2.html)，[PETA](http://mmlab.ie.cuhk.edu.hk/projects/PETA.html)和部分业务数据融合训练测试得到“。这部分业务数据应该起了很重要的作用。

还得是Paddle
