### ISSUE TITLE
Data augmentations

### ISSUE THREAD

**Issue by oho123dt** [valencebond/Rethinking_of_PAR#13]
I notice that there are many method of data augmentations mentioned in the Ablation Study in the paper. I assume this is relate to the "_C.TRAIN.DATAAUG.TYPE = 'base' " part in the config. How can I use this to test different types of data augmentation as suggested in the paper?

**Comment by valencebond** [comment]
Thanks for your attention. Augmentation in the ablation study is not implemented in current codes. You can change the augmentation code by yourself.
