### ISSUE TITLE
35 Attributes in PETA

### ISSUE THREAD

**Issue by LuongDucLong** [valencebond/Rethinking_of_PAR#16]
I can't find anything about the names of 35 selected attributes in PETA for training and evaluate. Can you help me?

**Comment by valencebond** [comment]
the names of 35 selected attributes are given in https://github.com/valencebond/Rethinking_of_PAR/tree/master/dataset/pedes_attr/annotation.md

**Comment by LuongDucLong** [comment]
Thank you for the names. But I have more one question. I've trained this repo with the PETA dataset and the best performance is 0.84 (so great!) but the prediction is a vector of 35 real number elements like below: 
`[-3.2106216  -4.670642    1.6492792  -4.8801847   0.39333236  1.681232
 -1.8524233  -4.342129   -5.8833485  -6.9158034  -5.9174     -6.236504
 -5.143317    0.7512278  -4.808728    2.230589   -2.5173874  -1.8406242
 -6.652723   -5.893917    1.8199699  -2.253507   -6.474844   -0.6732643
 -1.6438735  -7.163587    0.28714532 -1.6119152  -1.4690831  -5.146917
 -2.516921    0.5069503  -3.2760105  -6.259575    0.43772826]`

What threshold should I choose to convert this vector to class labels?

**Comment by tuantran23012000** [comment]
> Thank you for the names. But I have more one question. I've trained this repo with the PETA dataset and the best performance is 0.84 (so great!) but the prediction is a vector of 35 real number elements like below: `[-3.2106216 -4.670642 1.6492792 -4.8801847 0.39333236 1.681232 -1.8524233 -4.342129 -5.8833485 -6.9158034 -5.9174 -6.236504 -5.143317 0.7512278 -4.808728 2.230589 -2.5173874 -1.8406242 -6.652723 -5.893917 1.8199699 -2.253507 -6.474844 -0.6732643 -1.6438735 -7.163587 0.28714532 -1.6119152 -1.4690831 -5.146917 -2.516921 0.5069503 -3.2760105 -6.259575 0.43772826]`
> 
> What threshold should I choose to convert this vector to class labels?

Did you pass your prediction via sigmoid function?

**Comment by LuongDucLong** [comment]
> > Thank you for the names. But I have more one question. I've trained this repo with the PETA dataset and the best performance is 0.84 (so great!) but the prediction is a vector of 35 real number elements like below: `[-3.2106216 -4.670642 1.6492792 -4.8801847 0.39333236 1.681232 -1.8524233 -4.342129 -5.8833485 -6.9158034 -5.9174 -6.236504 -5.143317 0.7512278 -4.808728 2.230589 -2.5173874 -1.8406242 -6.652723 -5.893917 1.8199699 -2.253507 -6.474844 -0.6732643 -1.6438735 -7.163587 0.28714532 -1.6119152 -1.4690831 -5.146917 -2.516921 0.5069503 -3.2760105 -6.259575 0.43772826]`
> > What threshold should I choose to convert this vector to class labels?
> 
> Did you pass your prediction via sigmoid function?

I've not understood your answer, @tuantran23012000 . I think my prediction is a 35-d vector representing for 35 attributes, and I need a threshold to classify them to yes or no. What I get if my prediction pass through a sigmoid function?

**Comment by tuantran23012000** [comment]
> > > Thank you for the names. But I have more one question. I've trained this repo with the PETA dataset and the best performance is 0.84 (so great!) but the prediction is a vector of 35 real number elements like below: `[-3.2106216 -4.670642 1.6492792 -4.8801847 0.39333236 1.681232 -1.8524233 -4.342129 -5.8833485 -6.9158034 -5.9174 -6.236504 -5.143317 0.7512278 -4.808728 2.230589 -2.5173874 -1.8406242 -6.652723 -5.893917 1.8199699 -2.253507 -6.474844 -0.6732643 -1.6438735 -7.163587 0.28714532 -1.6119152 -1.4690831 -5.146917 -2.516921 0.5069503 -3.2760105 -6.259575 0.43772826]`
> > > What threshold should I choose to convert this vector to class labels?
> > 
> > 
> > Did you pass your prediction via sigmoid function?
> 
> I've not understood your answer, @tuantran23012000 . I think my prediction is a 35-d vector representing for 35 attributes, and I need a threshold to classify them to yes or no. What I get if my prediction pass through a sigmoid function?

Each of coordinates is a probability value in [0,1]. Hence, you need to pass via sigmoid function.
