### ISSUE TITLE
what is loss_w mean in /batch_engine.py#L51

### ISSUE THREAD

**Issue by momohuangsha** [valencebond/Rethinking_of_PAR#23]
hi~ @valencebond thks for your great work !
I don't understand what is loss_w mean? https://github.com/valencebond/Rethinking_of_PAR/blob/0baa46260707e02dfdbcbdbf61d6dbbcb79c0be7/batch_engine.py#L51

I noticed loss_w is set as default to [1,]
When do I need to set this parameter？like [1,1,1,] or [1,2,3,] etc..

**Comment by valencebond** [comment]
Due to only one loss used in my implementation, the loss_w (a list) is [1, ] to weight the binary cross entropy loss. You can reset the parameter when you have multiple losses.
