### ISSUE TITLE
Could you provide us training configuration more precisely?

### ISSUE THREAD

**Issue by macarize** [valencebond/Rethinking_of_PAR#4]
I trained your model with swin_s for PA100K but there was noticable gap between my experiment(79.48) and your reported performance(80.35)
I assume that configuration i used for training is different from your settings.
Could you provide us more precise configuration for swin_s (PA100K)?
many thanks.

**Comment by valencebond** [comment]
hi @macarize I train the swin_s model by replacing the BACKBONE.TYPE as "swin_s" in pa100k.yaml. Other configurations all remain the same. What is the epoch of your performance?
