### ISSUE TITLE
peta mat

### ISSUE THREAD

**Issue by Carringbrinks** [valencebond/Rethinking_of_PAR#6]

**Comment by Carringbrinks** [comment]
Where to get the mat file in peta data, please consult

**Comment by Vebrun** [comment]
兄弟你找到PTETA.mat了吗？

**Comment by tangsipeng** [comment]
https://github.com/ZJ96/deeplearning_project/tree/master/pedestrian_attribute_recognition

**Comment by Vebrun** [comment]
兄弟真给力 谢谢！！！
