### ISSUE TITLE
PETAzs and RAPV2zs download link

### ISSUE THREAD

**Issue by chaitrasj** [valencebond/Rethinking_of_PAR#7]
Hello,

Thank you for releasing the code for this awesome work!
I wanted to know how to access the proposed datasets in the paper: PETAzs and RAPv2 zs?
From where can we download these datasets also which scripts we need to run to keep the dataset in required file structure?

Thank you in advance!

**Comment by tangsipeng** [comment]
see dataset_zs_run0.pkl

**Comment by Antlerkeke** [comment]
in dataset_zs_run0.pkl，it only has “root：/mnt/data1/jiajian/datasets/attribute/PETA/images” no download links，I  also want to know how to access the proposed datasets in the paper: PETAzs and RAPv2 zs.

**Comment by valencebond** [comment]
> in dataset_zs_run0.pkl，it only has “root：/mnt/data1/jiajian/datasets/attribute/PETA/images” no download links，I also want to know how to access the proposed datasets in the paper: PETAzs and RAPv2 zs.

the images in PETAzs and RAPzs are collected from original PETA and RAPv2 datasets. So you should first download PETA and RAP datasets following the readme file.
