### ISSUE TITLE
Found some mistake in training

### ISSUE THREAD

**Issue by tangsipeng** [valencebond/Rethinking_of_PAR#9]
In my  training RAP2, i follow as readme mention, but found in the log: "RAP2 attr_num : 54, eval_attr_num : 54", and testing the saving model file " with shape torch.Size([54, 2048]) from checkpoint "
i think attr_num  must be 119 as readme said "Training on all attributes, testing on "selected" attribute." 
so in rapv2.yaml it should be " LABEL: 'all' " instead of " LABEL: 'eval' " , am i right  ?

**Comment by valencebond** [comment]
Some annotated attributes are not used in training and test according to papers of datasets.
